server:
  port: 8080  //配置端口
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url : jdbc:mysql://120.76.192.143:12108/wallet?useUnicode=true&characterEncoding=utf8mb4&allowPublicKeyRetrieval=true
    username : root
    password : hoodb1941
    driverClassName : com.mysql.cj.jdbc.Driver
